# Generated by Django 4.2.3 on 2023-08-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisements81', '0004_advertisements81_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisements81',
            name='image',
            field=models.ImageField(default='', upload_to='advertisements/', verbose_name='изображение'),
            preserve_default=False,
        ),
    ]
